name: EasyCheck

volumes:
  pgdata:

services:

  pgdb:
    image: postgres:17

    restart: always

    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

    volumes:
      - pgdata:/var/lib/postgresql

    ports:
      - "15432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready"]
      start_period: 1s
      start_interval: 1s
      interval: 60s
      timeout: 5s
      retries: 2


  app:
    build: .

    ports:
      - "8000:80"

    environment:
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_PORT=5432
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=pgdb
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - SECRET_KEY=${SECRET_KEY}

    depends_on:
      pgdb:
        condition: service_healthy
