name: EasyCheck

volumes:
  pgdata:

services:

  pgdb:
    image: postgres:17

    restart: always

    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    volumes:
      - pgdata:/var/lib/postgresql

    ports:
      - "15432:5432"

  app:
    build: .

    ports:
      - "8000:80"

    environment:
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_HOST=pgdb
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
      - SECRET_KEY=Xb899MTyQNtVHDX0k5Y2vvePcdoS952QVZZQo3lg-xYU

    depends_on:
      - pgdb
